# Generated by Django 4.2.16 on 2026-08-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinito_sonido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(max_length=50)),
                ('apellido_emp', models.CharField(max_length=50)),
                ('telefono_emp', models.CharField(max_length=20)),
                ('email_emp', models.EmailField(max_length=254)),
            ],
        ),
    ]
