# Generated by Django 4.2.16 on 2026-08-18 01:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infinito_sonido', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('estado_equipo', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('EN_REPARACION', 'En reparación')], default='DISPONIBLE', max_length=20)),
                ('cantidad_equipo', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='EquipoPorServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad requerida')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_asociados', to='infinito_sonido.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Equipo por Servicio',
                'verbose_name_plural': 'Equipos por Servicio',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipoeq', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion_servicio', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio base')),
                ('equipos', models.ManyToManyField(blank=True, related_name='servicios', through='infinito_sonido.EquipoPorServicio', to='infinito_sonido.equipo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='equipoporservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_equipos', to='infinito_sonido.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.tipoequipo'),
        ),
        migrations.AlterUniqueTogether(
            name='equipoporservicio',
            unique_together={('servicio', 'equipo')},
        ),
    ]
