# Generated by Django 4.2.16 on 2026-08-22 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infinito_sonido', '0003_equipo_equipoporservicio_tipoequipo_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('domicilio_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.IntegerField()),
                ('email_cliente', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Detalles_de_Pago',
            fields=[
                ('id_detalle_pago', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
            },
        ),
        migrations.CreateModel(
            name='Detalles_Reservas',
            fields=[
                ('id_detalle_reserva', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Detalle de Reserva',
                'verbose_name_plural': 'Detalles Reservas',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=50)),
                ('apellido_emp', models.CharField(max_length=50)),
                ('telefono_emp', models.IntegerField()),
                ('email_emp', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('estado_equipo', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('EN_REPARACION', 'En reparación')], default='DISPONIBLE', max_length=20)),
                ('cantidad_equipo', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Equipos_x_Servicios',
            fields=[
                ('id_equipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.equipos')),
            ],
            options={
                'verbose_name': 'Equipo x Servicio',
                'verbose_name_plural': 'Equipos x Servicios',
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_horas', models.FloatField()),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Horarios_x_Empleados',
            fields=[
                ('id_horario_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.empleados')),
                ('id_horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.horarios')),
            ],
            options={
                'verbose_name': 'Horario x Empleado',
                'verbose_name_plural': 'Horarios x Empleados',
                'unique_together': {('id_empleado', 'id_horario')},
            },
        ),
        migrations.CreateModel(
            name='Metodo_Pagos',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Método de Pagos',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField(default=0)),
                ('saldo_pendiente', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_perfil', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Puestos_x_Empleados',
            fields=[
                ('id_puesto_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.empleados')),
                ('id_puesto', models.ForeignKey(db_column='id_puesto', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.puestos')),
            ],
            options={
                'verbose_name': 'Puesto x Empleado',
                'verbose_name_plural': 'Puestos x Empleados',
                'unique_together': {('id_empleado', 'id_puesto')},
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateField()),
                ('direccion_evento', models.CharField(max_length=100)),
                ('duracion_evento', models.TimeField()),
                ('monto_total', models.FloatField(default=0)),
                ('estado_reserva', models.BooleanField(default=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.clientes')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Reservas_x_Servicios',
            fields=[
                ('id_reserva_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.reservas')),
            ],
            options={
                'verbose_name': 'Reserva x Servicio',
                'verbose_name_plural': 'Reservas x Servicios',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('precio_servicio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Sueldos',
            fields=[
                ('id_sueldo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_sueldo', models.FloatField()),
            ],
            options={
                'verbose_name': 'Sueldo',
                'verbose_name_plural': 'Sueldos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Equipos',
            fields=[
                ('id_tipoeq', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipoeq', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipo de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.perfiles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.AlterUniqueTogether(
            name='equipoporservicio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='equipoporservicio',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='equipoporservicio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='id_sueldo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='equipos',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='EquipoPorServicio',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Sueldo',
        ),
        migrations.DeleteModel(
            name='TipoEquipo',
        ),
        migrations.AddField(
            model_name='reservas_x_servicios',
            name='id_servicio',
            field=models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.servicios'),
        ),
        migrations.AddField(
            model_name='puestos',
            name='id_sueldo',
            field=models.ForeignKey(db_column='id_sueldo', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.sueldos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='id_reserva',
            field=models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.reservas'),
        ),
        migrations.AddField(
            model_name='equipos_x_servicios',
            name='id_servicio',
            field=models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.servicios'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='id_tipoeq',
            field=models.ForeignKey(db_column='id_tipoeq', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.tipo_equipos'),
        ),
        migrations.AddField(
            model_name='detalles_reservas',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.empleados'),
        ),
        migrations.AddField(
            model_name='detalles_reservas',
            name='id_reserva',
            field=models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.reservas'),
        ),
        migrations.AddField(
            model_name='detalles_de_pago',
            name='id_metodo_pago',
            field=models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, to='infinito_sonido.metodo_pagos'),
        ),
        migrations.AddField(
            model_name='detalles_de_pago',
            name='id_pago',
            field=models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, to='infinito_sonido.pagos'),
        ),
        migrations.AlterUniqueTogether(
            name='reservas_x_servicios',
            unique_together={('id_reserva', 'id_servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='equipos_x_servicios',
            unique_together={('id_equipo', 'id_servicio')},
        ),
    ]
