# Generated by Django 4.2.16 on 2026-09-13 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinito_sonido', '0014_usuarios_datos_personales_y_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
