# Hito 3 - paso 2: cantidad de unidades de cada equipo que usa un servicio
# (Equipos_x_Servicios.cantidad). Con esto la reserva controla la disponibilidad
# de equipos por día. Las relaciones que ya existían quedan con cantidad 1.

# Generated by Django 4.2.16 on 2026-10-06 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinito_sonido', '0020_reservas_hito3'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos_x_servicios',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
