-- =====================================================================
-- INFINITO SONIDO E ILUMINACION - Script 2 de 3: DATOS INICIALES
-- =====================================================================
-- Datos que el sistema necesita para funcionar, que normalmente cargan
-- las migraciones de Django:
--   - infinito_sonido_permisos: los 30 permisos (ver_/gestionar_ de cada
--     módulo, ver_registro y anular_reservas)
--   - infinito_sonido_estado_equipos: Disponible, En uso, En reparación
--   - django_migrations, django_content_type, auth_permission: control
--     interno de Django, para que sepa que la base ya está al día y no
--     intente crear las tablas de nuevo.
-- Cargar después de 01_estructura.sql.
-- =====================================================================


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `infinito_sonido_permisos` WRITE;
/*!40000 ALTER TABLE `infinito_sonido_permisos` DISABLE KEYS */;
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (1,'Ver Equipos','Permite ver el listado de Equipos.',1,'ver_equipos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (2,'Gestionar Equipos','Permite crear, editar y eliminar en Equipos.',1,'gestionar_equipos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (3,'Ver Clientes','Permite ver el listado de Clientes.',1,'ver_clientes',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (4,'Gestionar Clientes','Permite crear, editar y eliminar en Clientes.',1,'gestionar_clientes',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (5,'Ver Empleados','Permite ver el listado de Empleados.',1,'ver_empleados',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (6,'Gestionar Empleados','Permite crear, editar y eliminar en Empleados.',1,'gestionar_empleados',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (7,'Ver Servicios','Permite ver el listado de Servicios.',1,'ver_servicios',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (8,'Gestionar Servicios','Permite crear, editar y eliminar en Servicios.',1,'gestionar_servicios',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (9,'Ver Reservas','Permite ver el listado de Reservas.',1,'ver_reservas',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (10,'Gestionar Reservas','Permite crear, editar y eliminar en Reservas.',1,'gestionar_reservas',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (11,'Ver Perfiles','Permite ver el listado de Perfiles.',1,'ver_perfiles',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (12,'Gestionar Perfiles','Permite crear, editar y eliminar en Perfiles.',1,'gestionar_perfiles',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (13,'Ver Permisos','Permite ver el listado de Permisos.',1,'ver_permisos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (14,'Gestionar Permisos','Permite crear, editar y eliminar en Permisos.',1,'gestionar_permisos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (15,'Ver Usuarios','Permite ver el listado de Usuarios.',1,'ver_usuarios',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (16,'Gestionar Usuarios','Permite crear, editar y eliminar en Usuarios.',1,'gestionar_usuarios',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (17,'Ver Puestos','Permite ver el listado de Puestos.',1,'ver_puestos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (18,'Gestionar Puestos','Permite crear, editar y eliminar en Puestos.',1,'gestionar_puestos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (19,'Ver Sueldos','Permite ver el listado de Sueldos.',1,'ver_sueldos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (20,'Gestionar Sueldos','Permite crear, editar y eliminar en Sueldos.',1,'gestionar_sueldos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (21,'Ver Tipos de equipo','Permite ver el listado de Tipos de equipo.',1,'ver_tipos_equipo',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (22,'Gestionar Tipos de equipo','Permite crear, editar y eliminar en Tipos de equipo.',1,'gestionar_tipos_equipo',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (23,'Ver Horarios','Permite ver el listado de Horarios.',1,'ver_horarios',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (24,'Gestionar Horarios','Permite crear, editar y eliminar en Horarios.',1,'gestionar_horarios',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (25,'Ver Métodos de pago','Permite ver el listado de Métodos de pago.',1,'ver_metodos_pago',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (26,'Gestionar Métodos de pago','Permite crear, editar y eliminar en Métodos de pago.',1,'gestionar_metodos_pago',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (27,'Ver Pagos','Permite ver el listado de Pagos.',1,'ver_pagos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (28,'Gestionar Pagos','Permite crear, editar y eliminar en Pagos.',1,'gestionar_pagos',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (29,'Ver Registro de actividad','Permite ver quién hizo cada alta, modificación y baja, los inicios de sesión y los errores del sistema.',1,'ver_registro',1,NULL);
INSERT INTO `infinito_sonido_permisos` (`id_permiso`, `nombre_permiso`, `descripcion_permiso`, `estado_permiso`, `codigo`, `activo`, `fecha_baja`) VALUES (30,'Anular Reservas','Permite anular una reserva indicando el motivo. La reserva no se borra: queda como Anulada.',1,'anular_reservas',1,NULL);
/*!40000 ALTER TABLE `infinito_sonido_permisos` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `infinito_sonido_estado_equipos` WRITE;
/*!40000 ALTER TABLE `infinito_sonido_estado_equipos` DISABLE KEYS */;
INSERT INTO `infinito_sonido_estado_equipos` (`id_estadoeq`, `nombre_estadoeq`, `activo`, `fecha_baja`) VALUES (1,'Disponible',1,NULL);
INSERT INTO `infinito_sonido_estado_equipos` (`id_estadoeq`, `nombre_estadoeq`, `activo`, `fecha_baja`) VALUES (2,'En uso',1,NULL);
INSERT INTO `infinito_sonido_estado_equipos` (`id_estadoeq`, `nombre_estadoeq`, `activo`, `fecha_baja`) VALUES (3,'En reparación',1,NULL);
/*!40000 ALTER TABLE `infinito_sonido_estado_equipos` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `django_content_type` WRITE;
/*!40000 ALTER TABLE `django_content_type` DISABLE KEYS */;
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (1,'admin','logentry');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (3,'auth','group');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (2,'auth','permission');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (4,'auth','user');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (5,'contenttypes','contenttype');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (7,'infinito_sonido','clientes');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (8,'infinito_sonido','detalles_de_pago');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (9,'infinito_sonido','detalles_reservas');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (10,'infinito_sonido','empleados');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (11,'infinito_sonido','equipos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (12,'infinito_sonido','equipos_x_servicios');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (29,'infinito_sonido','estado_equipos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (13,'infinito_sonido','horarios');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (14,'infinito_sonido','horarios_x_empleados');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (15,'infinito_sonido','metodo_pagos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (16,'infinito_sonido','pagos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (17,'infinito_sonido','perfiles');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (26,'infinito_sonido','permisos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (27,'infinito_sonido','permisos_x_perfiles');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (18,'infinito_sonido','puestos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (19,'infinito_sonido','puestos_x_empleados');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (30,'infinito_sonido','registro_actividad');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (20,'infinito_sonido','reservas');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (21,'infinito_sonido','reservas_x_servicios');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (22,'infinito_sonido','servicios');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (28,'infinito_sonido','sesiontoken');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (23,'infinito_sonido','sueldos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (24,'infinito_sonido','tipo_equipos');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (31,'infinito_sonido','token_recuperacion');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (25,'infinito_sonido','usuarios');
INSERT INTO `django_content_type` (`id`, `app_label`, `model`) VALUES (6,'sessions','session');
/*!40000 ALTER TABLE `django_content_type` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `auth_permission` WRITE;
/*!40000 ALTER TABLE `auth_permission` DISABLE KEYS */;
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (1,'Can add log entry',1,'add_logentry');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (2,'Can change log entry',1,'change_logentry');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (3,'Can delete log entry',1,'delete_logentry');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (4,'Can view log entry',1,'view_logentry');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (5,'Can add permission',2,'add_permission');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (6,'Can change permission',2,'change_permission');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (7,'Can delete permission',2,'delete_permission');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (8,'Can view permission',2,'view_permission');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (9,'Can add group',3,'add_group');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (10,'Can change group',3,'change_group');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (11,'Can delete group',3,'delete_group');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (12,'Can view group',3,'view_group');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (13,'Can add user',4,'add_user');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (14,'Can change user',4,'change_user');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (15,'Can delete user',4,'delete_user');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (16,'Can view user',4,'view_user');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (17,'Can add content type',5,'add_contenttype');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (18,'Can change content type',5,'change_contenttype');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (19,'Can delete content type',5,'delete_contenttype');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (20,'Can view content type',5,'view_contenttype');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (21,'Can add session',6,'add_session');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (22,'Can change session',6,'change_session');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (23,'Can delete session',6,'delete_session');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (24,'Can view session',6,'view_session');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (25,'Can add Cliente',7,'add_clientes');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (26,'Can change Cliente',7,'change_clientes');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (27,'Can delete Cliente',7,'delete_clientes');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (28,'Can view Cliente',7,'view_clientes');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (29,'Can add Detalle de Pago',8,'add_detalles_de_pago');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (30,'Can change Detalle de Pago',8,'change_detalles_de_pago');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (31,'Can delete Detalle de Pago',8,'delete_detalles_de_pago');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (32,'Can view Detalle de Pago',8,'view_detalles_de_pago');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (33,'Can add Detalle de Reserva',9,'add_detalles_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (34,'Can change Detalle de Reserva',9,'change_detalles_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (35,'Can delete Detalle de Reserva',9,'delete_detalles_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (36,'Can view Detalle de Reserva',9,'view_detalles_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (37,'Can add Empleado',10,'add_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (38,'Can change Empleado',10,'change_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (39,'Can delete Empleado',10,'delete_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (40,'Can view Empleado',10,'view_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (41,'Can add Equipo',11,'add_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (42,'Can change Equipo',11,'change_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (43,'Can delete Equipo',11,'delete_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (44,'Can view Equipo',11,'view_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (45,'Can add Equipo x Servicio',12,'add_equipos_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (46,'Can change Equipo x Servicio',12,'change_equipos_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (47,'Can delete Equipo x Servicio',12,'delete_equipos_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (48,'Can view Equipo x Servicio',12,'view_equipos_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (49,'Can add Horario',13,'add_horarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (50,'Can change Horario',13,'change_horarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (51,'Can delete Horario',13,'delete_horarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (52,'Can view Horario',13,'view_horarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (53,'Can add Horario x Empleado',14,'add_horarios_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (54,'Can change Horario x Empleado',14,'change_horarios_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (55,'Can delete Horario x Empleado',14,'delete_horarios_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (56,'Can view Horario x Empleado',14,'view_horarios_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (57,'Can add Método de Pago',15,'add_metodo_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (58,'Can change Método de Pago',15,'change_metodo_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (59,'Can delete Método de Pago',15,'delete_metodo_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (60,'Can view Método de Pago',15,'view_metodo_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (61,'Can add Pago',16,'add_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (62,'Can change Pago',16,'change_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (63,'Can delete Pago',16,'delete_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (64,'Can view Pago',16,'view_pagos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (65,'Can add Perfil',17,'add_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (66,'Can change Perfil',17,'change_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (67,'Can delete Perfil',17,'delete_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (68,'Can view Perfil',17,'view_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (69,'Can add Puesto',18,'add_puestos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (70,'Can change Puesto',18,'change_puestos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (71,'Can delete Puesto',18,'delete_puestos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (72,'Can view Puesto',18,'view_puestos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (73,'Can add Puesto x Empleado',19,'add_puestos_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (74,'Can change Puesto x Empleado',19,'change_puestos_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (75,'Can delete Puesto x Empleado',19,'delete_puestos_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (76,'Can view Puesto x Empleado',19,'view_puestos_x_empleados');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (77,'Can add Reserva',20,'add_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (78,'Can change Reserva',20,'change_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (79,'Can delete Reserva',20,'delete_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (80,'Can view Reserva',20,'view_reservas');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (81,'Can add Reserva x Servicio',21,'add_reservas_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (82,'Can change Reserva x Servicio',21,'change_reservas_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (83,'Can delete Reserva x Servicio',21,'delete_reservas_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (84,'Can view Reserva x Servicio',21,'view_reservas_x_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (85,'Can add Servicio',22,'add_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (86,'Can change Servicio',22,'change_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (87,'Can delete Servicio',22,'delete_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (88,'Can view Servicio',22,'view_servicios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (89,'Can add Sueldo',23,'add_sueldos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (90,'Can change Sueldo',23,'change_sueldos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (91,'Can delete Sueldo',23,'delete_sueldos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (92,'Can view Sueldo',23,'view_sueldos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (93,'Can add Tipo de Equipo',24,'add_tipo_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (94,'Can change Tipo de Equipo',24,'change_tipo_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (95,'Can delete Tipo de Equipo',24,'delete_tipo_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (96,'Can view Tipo de Equipo',24,'view_tipo_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (97,'Can add Usuario',25,'add_usuarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (98,'Can change Usuario',25,'change_usuarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (99,'Can delete Usuario',25,'delete_usuarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (100,'Can view Usuario',25,'view_usuarios');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (101,'Can add Permiso',26,'add_permisos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (102,'Can change Permiso',26,'change_permisos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (103,'Can delete Permiso',26,'delete_permisos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (104,'Can view Permiso',26,'view_permisos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (105,'Can add Permiso x Perfil',27,'add_permisos_x_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (106,'Can change Permiso x Perfil',27,'change_permisos_x_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (107,'Can delete Permiso x Perfil',27,'delete_permisos_x_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (108,'Can view Permiso x Perfil',27,'view_permisos_x_perfiles');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (109,'Can add Sesión (token)',28,'add_sesiontoken');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (110,'Can change Sesión (token)',28,'change_sesiontoken');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (111,'Can delete Sesión (token)',28,'delete_sesiontoken');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (112,'Can view Sesión (token)',28,'view_sesiontoken');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (113,'Can add Estado de Equipo',29,'add_estado_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (114,'Can change Estado de Equipo',29,'change_estado_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (115,'Can delete Estado de Equipo',29,'delete_estado_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (116,'Can view Estado de Equipo',29,'view_estado_equipos');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (117,'Can add Registro de actividad',30,'add_registro_actividad');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (118,'Can change Registro de actividad',30,'change_registro_actividad');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (119,'Can delete Registro de actividad',30,'delete_registro_actividad');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (120,'Can view Registro de actividad',30,'view_registro_actividad');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (121,'Can add Token de recuperación',31,'add_token_recuperacion');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (122,'Can change Token de recuperación',31,'change_token_recuperacion');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (123,'Can delete Token de recuperación',31,'delete_token_recuperacion');
INSERT INTO `auth_permission` (`id`, `name`, `content_type_id`, `codename`) VALUES (124,'Can view Token de recuperación',31,'view_token_recuperacion');
/*!40000 ALTER TABLE `auth_permission` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `django_migrations` WRITE;
/*!40000 ALTER TABLE `django_migrations` DISABLE KEYS */;
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (1,'contenttypes','0001_initial','2026-10-07 03:22:58.450696');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (2,'auth','0001_initial','2026-10-07 03:22:59.181382');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (3,'admin','0001_initial','2026-10-07 03:22:59.372651');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (4,'admin','0002_logentry_remove_auto_add','2026-10-07 03:22:59.382280');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (5,'admin','0003_logentry_add_action_flag_choices','2026-10-07 03:22:59.390391');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (6,'contenttypes','0002_remove_content_type_name','2026-10-07 03:22:59.535144');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (7,'auth','0002_alter_permission_name_max_length','2026-10-07 03:22:59.612843');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (8,'auth','0003_alter_user_email_max_length','2026-10-07 03:22:59.630500');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (9,'auth','0004_alter_user_username_opts','2026-10-07 03:22:59.639436');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (10,'auth','0005_alter_user_last_login_null','2026-10-07 03:22:59.700742');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (11,'auth','0006_require_contenttypes_0002','2026-10-07 03:22:59.706313');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (12,'auth','0007_alter_validators_add_error_messages','2026-10-07 03:22:59.714084');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (13,'auth','0008_alter_user_username_max_length','2026-10-07 03:22:59.787804');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (14,'auth','0009_alter_user_last_name_max_length','2026-10-07 03:22:59.877263');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (15,'auth','0010_alter_group_name_max_length','2026-10-07 03:22:59.902226');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (16,'auth','0011_update_proxy_permissions','2026-10-07 03:22:59.911914');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (17,'auth','0012_alter_user_first_name_max_length','2026-10-07 03:23:00.004319');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (18,'infinito_sonido','0001_initial','2026-10-07 03:23:00.154687');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (19,'infinito_sonido','0002_empleado','2026-10-07 03:23:00.184508');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (20,'infinito_sonido','0003_equipo_equipoporservicio_tipoequipo_servicio_and_more','2026-10-07 03:23:00.551305');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (21,'infinito_sonido','0004_clientes_detalles_de_pago_detalles_reservas_and_more','2026-10-07 03:23:03.150319');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (22,'infinito_sonido','0005_permisos_permisos_x_perfiles_and_more','2026-10-07 03:23:03.504568');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (23,'infinito_sonido','0006_sesiontoken','2026-10-07 03:23:03.613603');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (24,'infinito_sonido','0007_reservas_nombre_evento_alter_reservas_estado_reserva','2026-10-07 03:23:03.801176');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (25,'infinito_sonido','0008_estado_equipos','2026-10-07 03:23:04.229886');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (26,'infinito_sonido','0009_permisos_codigo_y_seed','2026-10-07 03:23:04.381134');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (27,'infinito_sonido','0010_alter_clientes_telefono_cliente_and_more','2026-10-07 03:23:04.563801');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (28,'infinito_sonido','0011_permisos_puestos_sueldos','2026-10-07 03:23:04.590090');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (29,'infinito_sonido','0012_validar_nombres_y_domicilio','2026-10-07 03:23:04.915066');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (30,'infinito_sonido','0013_permisos_modulos_faltantes','2026-10-07 03:23:04.940251');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (31,'infinito_sonido','0014_usuarios_datos_personales_y_baja','2026-10-07 03:23:05.640623');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (32,'infinito_sonido','0015_alter_pagos_monto','2026-10-07 03:23:05.647416');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (33,'infinito_sonido','0016_reservas_hora_y_duracion','2026-10-07 03:23:05.814913');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (34,'infinito_sonido','0017_usuarios_desde_empleados','2026-10-07 03:23:06.412578');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (35,'infinito_sonido','0018_registro_actividad','2026-10-07 03:23:06.565843');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (36,'infinito_sonido','0019_token_recuperacion','2026-10-07 03:23:06.682381');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (37,'infinito_sonido','0020_reservas_hito3','2026-10-07 03:23:07.218981');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (38,'infinito_sonido','0021_equipos_x_servicios_cantidad','2026-10-07 03:23:07.308564');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (39,'infinito_sonido','0022_usuarios_apellido_inicial','2026-10-07 03:23:07.326707');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (40,'infinito_sonido','0023_baja_logica','2026-10-07 03:23:08.811309');
INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES (41,'sessions','0001_initial','2026-10-07 03:23:08.861887');
/*!40000 ALTER TABLE `django_migrations` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

